
package com.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WService", targetNamespace = "http://service.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WService {


    /**
     * 
     * @param password
     * @param arg5
     * @param sicil
     * @param surname
     * @param name
     * @param department
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.com/WService/newUserRequest", output = "http://service.com/WService/newUserResponse")
    public String newUser(
        @WebParam(name = "Sicil", partName = "Sicil")
        int sicil,
        @WebParam(name = "Surname", partName = "Surname")
        String surname,
        @WebParam(name = "Name", partName = "Name")
        String name,
        @WebParam(name = "Department", partName = "Department")
        String department,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "arg5", partName = "arg5")
        boolean arg5);

    /**
     * 
     * @param ad
     * @param sicil
     * @param soyad
     * @param departman
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.com/WService/addDatabaseRequest", output = "http://service.com/WService/addDatabaseResponse")
    public boolean addDatabase(
        @WebParam(name = "Sicil", partName = "Sicil")
        int sicil,
        @WebParam(name = "Soyad", partName = "Soyad")
        String soyad,
        @WebParam(name = "Ad", partName = "Ad")
        String ad,
        @WebParam(name = "Departman", partName = "Departman")
        String departman);

    /**
     * 
     * @param deger
     * @param sýra
     * @param sicil
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.com/WService/updateDatabaseRequest", output = "http://service.com/WService/updateDatabaseResponse")
    public boolean updateDatabase(
        @WebParam(name = "S\u0131ra", partName = "S\u0131ra")
        String sýra,
        @WebParam(name = "Deger", partName = "Deger")
        String deger,
        @WebParam(name = "Sicil", partName = "Sicil")
        int sicil);

    /**
     * 
     * @param sicil
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.com/WService/deleteDatabaseRequest", output = "http://service.com/WService/deleteDatabaseResponse")
    public boolean deleteDatabase(
        @WebParam(name = "Sicil", partName = "Sicil")
        int sicil);

}
