
package com.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WServImpService", targetNamespace = "http://service.com/", wsdlLocation = "http://localhost:8080/DataTable/hello?wsdl")
public class WServImpService
    extends Service
{

    private final static URL WSERVIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSERVIMPSERVICE_EXCEPTION;
    private final static QName WSERVIMPSERVICE_QNAME = new QName("http://service.com/", "WServImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DataTable/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSERVIMPSERVICE_WSDL_LOCATION = url;
        WSERVIMPSERVICE_EXCEPTION = e;
    }

    public WServImpService() {
        super(__getWsdlLocation(), WSERVIMPSERVICE_QNAME);
    }

    public WServImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSERVIMPSERVICE_QNAME, features);
    }

    public WServImpService(URL wsdlLocation) {
        super(wsdlLocation, WSERVIMPSERVICE_QNAME);
    }

    public WServImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSERVIMPSERVICE_QNAME, features);
    }

    public WServImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WServImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WService
     */
    @WebEndpoint(name = "WServImpPort")
    public WService getWServImpPort() {
        return super.getPort(new QName("http://service.com/", "WServImpPort"), WService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WService
     */
    @WebEndpoint(name = "WServImpPort")
    public WService getWServImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.com/", "WServImpPort"), WService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSERVIMPSERVICE_EXCEPTION!= null) {
            throw WSERVIMPSERVICE_EXCEPTION;
        }
        return WSERVIMPSERVICE_WSDL_LOCATION;
    }

}
